#nested dictionary
#first depth of keys are lines, in which all key/values of stop name/stop ids are provided for that particular line. 
#station ids should not include direction of train, like 636S or 636N, just 636
table = {"1":["Van Cortlandt Park - 242 St", "238 St", "231 St", "Marble Hill - 225 St", "215 St", "207 St", "Dyckman St", "191 St", "181 St", "168 St - Washington Hts", "157 St", "145 St", "137 St - City College", "125 St", "116 St - Columbia University", "Cathedral Pkwy (110 St)", "103 St", "96 St", "86 St", '79 St', '72 St', '66 St - Lincoln Center', '59 St - Columbus Circle', '50 St', 'Times Sq - 42 St', '34 St - Penn Station', '23 St', '18 St', '14 St', 'Christopher St - Sheridan Sq', 'Houston St', 'Canal St', 'Franklin St', 'Chambers St', 'WTC Cortlandt', 'Rector St', 'South Ferry'],
"2":['Wakefield - 241 St', 'Nereid Av', '233 St', '225 St', '219 St', 'Gun Hill Rd', 'Burke Av', 'Allerton Av', 'Pelham Pkwy', 'Bronx Park East', 'E 180 St', 'West Farms Sq - E Tremont Av', '174 St', 'Freeman St', 'Simpson St', 'Intervale Av', 'Prospect Av', '3 Av - 149 St', '149 St - Grand Concourse', '135 St', '125 St', '116 St', 'Central Park North (110 St)', '96 St', '86 St', '79 St', '72 St', '66 St - Lincoln Center', '59 St - Columbus Circle', '50 St', 'Times Sq - 42 St', '34 St - Penn Station', '28 St', '23 St', '18 St', '14 St', 'Christopher St - Sheridan Sq', 'Houston St', 'Canal St', 'Franklin St', 'Chambers St', 'Park Pl', 'Fulton St', 'Wall St', 'Clark St', 'Borough Hall', 'Hoyt St', 'Nevins St', 'Atlantic Av', 'Bergen St', 'Grand Army Plaza', 'Eastern Pkwy - Brooklyn Museum', 'Franklin Av', 'President St', 'Sterling St', 'Winthrop St', 'Church Av', 'Beverly Rd', 'Newkirk Av', 'Flatbush Av - Brooklyn College'],
'3':['Harlem - 148 St', '145 St', '135 St', '116 St', 'Central Park North (110 St)', '96 St', '72 St', 'Times Sq - 42 St', '34 St - Penn Station', '14 St', 'Chambers St', 'Park Pl', 'Fulton St', 'Wall St', 'Clark St', 'Borough Hall', 'Hoyt St', 'Nevins St', 'Atlantic Av', 'Bergen St', 'Grand Army Plaza', 'Eastern Pkwy - Brooklyn Museum', 'Franklin Av', 'Nostrand Av', 'Kingston Av', 'Crown Hts - Utica Av', 'Sutter Av - Rutland Rd', 'Saratoga Av', 'Rockaway Av', 'Junius St', 'Pennsylvania Av', 'Van Siclen Av', 'New Lots Av'],
'4':['Woodlawn', 'Mosholu Pkwy', 'Bedford Park Blvd - Lehman College', 'Kingsbridge Rd', 'Fordham Rd', '183 St', 'Burnside Av', '176 St', 'Mt Eden Av', '170 St', '167 St', '161 St - Yankee Stadium', '149 St - Grand Concourse', '138 St - Grand Concourse', '125 St', '116 St', '110 St', '103 St', '96 St', '86 St', '77 St', '68 St - Hunter College', '59 St', '51 St', 'Grand Central - 42 St', '33 St', '28 St', '23 St', '14 St - Union Sq', 'Astor Pl', 'Broadway-Lafayette St', 'Spring St', 'Canal St', 'Brooklyn Bridge - City Hall', 'Fulton St', 'Wall St', 'Bowling Green', 'Borough Hall', 'Nevins St', 'Atlantic Av', 'Bergen St', 'Grand Army Plaza', 'Eastern Pkwy - Brooklyn Museum', 'Franklin Av', 'Nostrand Av', 'Kingston Av', 'Crown Hts - Utica Av', 'Sutter Av - Rutland Rd', 'Saratoga Av', 'Rockaway Av', 'Junius St', 'Pennsylvania Av', 'Van Siclen Av', 'New Lots Av'],
'5':['Eastchester - Dyre Av', 'Baychester Av', 'Gun Hill Rd', 'Pelham Pkwy', 'Morris Park', 'Nereid Av', '233 St', '225 St', '219 St', 'Gun Hill Rd', 'Burke Av', 'Allerton Av', 'Pelham Pkwy', 'Bronx Park East', 'E 180 St', 'West Farms Sq - E Tremont Av', '174 St', 'Freeman St', 'Simpson St', 'Intervale Av', 'Prospect Av', 'Jackson Av', '149 St - Grand Concourse', '138 St - Grand Concourse', '125 St', '86 St', '59 St', 'Grand Central - 42 St', '14 St - Union Sq', 'Brooklyn Bridge - City Hall', 'Fulton St', 'Wall St', 'Bowling Green', 'Borough Hall', 'Nevins St', 'Atlantic Av', 'Franklin Av', 'President St', 'Sterling St', 'Winthrop St', 'Church Av', 'Beverly Rd', 'Newkirk Av', 'Flatbush Av - Brooklyn College'],
'6L':['Pelham Bay Park', 'Buhre Av', 'Middletown Rd', 'Westchester Sq - E Tremont Av', 'Zerega Av', 'Castle Hill Av', 'Parkchester', 'St Lawrence Av', 'Morrison Av- Sound View', 'Elder Av', 'Whitlock Av', 'Hunts Point Av', 'Longwood Av', 'E 149 St', "E 143 St - St Mary's St", 'Cypress Av', 'Brook Av', '3 Av - 138 St', '125 St', '116 St', '110 St', '103 St', '96 St', '86 St', '77 St', '68 St - Hunter College', '59 St', '51 St', 'Grand Central - 42 St', '33 St', '28 St', '23 St', '14 St - Union Sq', 'Astor Pl', 'Broadway-Lafayette St', 'Spring St', 'Canal St', 'Brooklyn Bridge - City Hall'],
'6E':[],
'7L':[],
'7E':[],
'A':[],
'B':[],
'C':[],
'D':[],
'E':[],
'F':[],
'G':[],
'J':[],
'L':[],
'M':[],
'N':[],
'Q':[],
'R':[],
'S':[],
'W':[],
'Z':[]}
